services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    labels:
      tested: "false"
      controller: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/config
    environment:
      CONFIG_PATH: /config/config.yaml
      OUTPUT_DIR: /config
    depends_on:
      - node-1
      - node-2
      - node-3


  node-1:
    init: true
    build:
      context: .
      dockerfile: Dockerfile.demo
    environment:
      - NODE_ID=1
    restart: always
    labels:
      tested: "true"
    ports:
      - "8081:8080"
    healthcheck:
      # apparently alpine doesnt have curl installed, gotta use wget
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  node-2:
    init: true
    build:
      context: .
      dockerfile: Dockerfile.demo
    environment:
      - NODE_ID=2
    restart: always
    labels:
      tested: "true"
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s


  node-3:
    init: true
    build:
      context: .
      dockerfile: Dockerfile.demo
    environment:
      - NODE_ID=3
    restart: always
    labels:
      tested: "true"
    ports:
      - "8083:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
