services:
  node-1:
    build:
      context: .
      dockerfile: Dockerfile.demo
    environment:
      - NODE_ID=1
    restart: always
    labels:
      tested: "true"
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

  node-2:
    build:
      context: .
      dockerfile: Dockerfile.demo
    environment:
      - NODE_ID=2
    restart: always
    labels:
      tested: "true"
    ports:
      - "8082:8080"

  node-3:
    build:
      context: .
      dockerfile: Dockerfile.demo
    environment:
      - NODE_ID=3
    restart: always
    labels:
      tested: "true"
    ports:
      - "8083:8080"
