services:
  node-1:
    build:
      context: .
      dockerfile: Dockerfile.demo
    environment:
      - NODE_ID=1
      - tested=true
    ports:
      - "8081:8080"

  node-2:
    build:
      context: .
      dockerfile: Dockerfile.demo
    environment:
      - NODE_ID=2
      - tested=true
    ports:
      - "8082:8080"

  node-3:
    build:
      context: .
      dockerfile: Dockerfile.demo
    environment:
      - NODE_ID=3
      - tested=true
    ports:
      - "8083:8080"
